### PR TITLE
Removed stopwords 

### LINKED ISSUE #2: Support other languages
All languages have words that you don't want to count like in Spanish with "La,el,los,nos, etc...". It is necessary to find a good way to ignore those words and that can be adapted to other languages (not just create a var that stores those words as it is now)

### PR DESCRIPTION
**Pull request by ObaidAshraf**
This should fix #2.
Added NLTK library to download list of stopwords. Currently English language is set as default language. The language can be changed and harcoded right now. 
I believe there should be an option to specify language in the GUI. A dropdown can be added to select a language such an 'english' or 'spanish' etc.

### CODE REVIEW

**Comment by dani0105** [comment]
if you add the dropdown for English and Spanish at least

**Comment by ObaidAshraf** [comment]
Yeah I can do this.. But I was planning to add this in #1 along with other UI updates..

what do you think?

**Comment by dani0105** [comment]
Ok

**Review by dani0105 — COMMENTED** [review]
The library works fine for detecting stopwords. Waiting for UI update to be able to select stopword language

**Pull request merged**
